### ISSUE TITLE
Fail when logged in with line and connect with google(its redirect to `localhost` instead of `periodpejai.vercel`

### ISSUE THREAD

**Issue by Tezigudo** [JiratchayaPhinyodom/Period-Pejai#75]
![image](https://user-images.githubusercontent.com/80502090/203480078-fbf4957f-b9c4-43f6-a161-8ab748d0e008.png)

![image](https://user-images.githubusercontent.com/80502090/203478893-e330046f-b8ca-4503-9c94-63a4ffcb2a22.png)

**Comment by JiratchayaPhinyodom** [comment]
Fixed
