### ISSUE TITLE
Have to fix CSS Media Queries when open with different devices

### ISSUE THREAD

**Issue by zevenfox** [JiratchayaPhinyodom/Period-Pejai#76]
<img width="663" alt="Screen Shot 2565-11-23 at 15 09 07" src="https://user-images.githubusercontent.com/64556398/203498060-d83b0536-b3f3-4b43-ad50-008c809edc62.png">
When minimize screen web should be working too. but very nice UI kub

**Comment by JiratchayaPhinyodom** [comment]
Not Defect
