### ISSUE TITLE
When click save, sometimes it not responsive

### ISSUE THREAD

**Issue by panitnt** [JiratchayaPhinyodom/Period-Pejai#82]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/92779345/203925719-105b9340-f5a3-49ea-92ed-a3dcb2017691.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/92779345/203926059-edbd7730-6dbb-443d-9082-7f439272a6fa.png">

**Comment by JiratchayaPhinyodom** [comment]
Fixed
