### ISSUE TITLE
After time I login my settings are shown as 0

### ISSUE THREAD

**Issue by jbrucker** [JiratchayaPhinyodom/Period-Pejai#87]
After logging in and completing the settings page, including birthyear, period length, etc.,
the next time I login it shows only 0 again, not the previously saved values.
[Period Pejai settings.pdf](https://github.com/JiratchayaPhinyodom/Period-Pejai/files/10100068/Period.Pejai.settings.pdf)

**Comment by JiratchayaPhinyodom** [comment]
I’ve set the limit of the birth year input because women will not have their period anymore when their age is more than 50-60.

**Comment by JiratchayaPhinyodom** [comment]
I already fiexed it and already redeploy. Please try again if you found the bugs please tell me I will fix it as soon as possible. (https://period-pejai-deploy.vercel.app/)
